# Generated by Django 3.0.5 on 2020-05-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('url', models.TextField(default='https://github.com/gavinuhran/')),
            ],
        ),
    ]
