# Generated by Django 3.0.5 on 2020-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200512_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproject',
            name='url',
            field=models.TextField(default='https://github.com/gavinuhran/'),
        ),
    ]
