# Generated by Django 3.0.5 on 2020-05-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200511_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.TextField(default='https://github.com/gavinuhran/'),
        ),
    ]
