# Generated by Django 3.0.5 on 2020-05-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_github_instagram_linkedin_twitter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePicture',
            new_name='Profile',
        ),
    ]
