# Generated by Django 3.0.5 on 2020-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200512_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutMe1', models.TextField()),
                ('aboutMe2', models.TextField()),
            ],
        ),
    ]
